// src/views/Favorites.vue
<template>
  <div class="wrapper">
    <div class="container">
      <h2>Favorites</h2>
      <favorite-field
        v-for="field in fields"
        :key="field.id"
        :name="field.name"
        :icon="field.icon"
        :value="field.value"
      />
      <button>Save</button>
    </div>
  </div>
</template>

<script>
import homeIcon from "@/assets/fav_home.png";
import workIcon from "@/assets/fav_work.png";
import schoolIcon from "@/assets/fav_school.png";
import newIcon from "@/assets/fav_new.png";

import FavoriteField from "@/components/FavoriteField.vue";
export default {
  components: {
    FavoriteField
  },
  data: function() {
    return {
      fields: [
        {
          id: 0,
          name: "Home",
          icon: homeIcon,
          value: ""
        },
        {
          id: 1,
          name: "Work",
          icon: workIcon,
          value: ""
        },
        {
          id: 2,
          name: "School",
          icon: schoolIcon,
          value: ""
        },
        {
          id: 3,
          name: "New",
          icon: newIcon,
          value: ""
        }
      ]
    };
  }
};
</script>


<style lang="scss" scoped>
@import "@/common/constants.scss";
@import "@/common/card.scss";

.wrapper {
  @extend %card;
}
</style>

// src/components/Favorites/Favorites.jsx
import React from "react";
import "./Favorites.scss";
import homeIcon from "../../assets/001-home.png";
import workIcon from "../../assets/002-work.png";
import schoolIcon from "../../assets/003-school.png";
import newIcon from "../../assets/004-more.png";

import FavoriteField from "./FavoriteField";

class Favorites extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      home: "",
      work: "",
      school: "",
      new: ""
    };
  }

  handleChange(event) {
    this.setState({ [event.target.id]: event.target.value });
  }

  render() {
    return (
      <div className="FavoritesContainer">
        <h2 className="FavoritesHeading">Favorites</h2>
        <FavoriteField
          value={this.state.home}
          name="home"
          icon={homeIcon}
          handleChange={e => this.handleChange(e)}
        />
        <FavoriteField
          value={this.state.work}
          name="work"
          icon={workIcon}
          handleChange={e => this.handleChange(e)}
        />
        <FavoriteField
          value={this.state.school}
          name="school"
          icon={schoolIcon}
          handleChange={e => this.handleChange(e)}
        />
        <FavoriteField
          value={this.state.new}
          name="new"
          icon={newIcon}
          handleChange={e => this.handleChange(e)}
        />
        <button className="FavoritesSubmit">Save</button>
      </div>
    );
  }
}

export default Favorites;
