// src/components/FavoriteField.vue
<template>
  <div class="FavoriteField">
    <img v-bind:src="icon" v-bind:alt="name">
    <input type="text" v-bind:value="value" v-bind:placeholder="name + ' address'">
  </div>
</template>

<script>
export default {
  props: {
    name: String,
    icon: String,
    value: String
  }
};
</script>

<style lang="scss" scoped>
.FavoriteField {
  display: flex;
  align-items: center;

  input {
    margin-left: 10px;
  }

  input::placeholder {
    text-transform: capitalize;
  }
}
</style>

// src/components/Favorites/FavoriteField.jsx
import React from "react";

const FavoriteField = ({ name, icon, value, handleChange }) => (
  <div className="FavoriteField">
    <img src={icon} alt={name} />
    <input
      id={name}
      type="text"
      value={value}
      onChange={handleChange}
      placeholder={name + " address"}
    />
  </div>
);

export default FavoriteField;
